//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksSalesClient.CustomerManagementServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailFromPartnersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailOptInField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailFromPartners {
            get {
                return this.EmailFromPartnersField;
            }
            set {
                if ((this.EmailFromPartnersField.Equals(value) != true)) {
                    this.EmailFromPartnersField = value;
                    this.RaisePropertyChanged("EmailFromPartners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailOptIn {
            get {
                return this.EmailOptInField;
            }
            set {
                if ((this.EmailOptInField.Equals(value) != true)) {
                    this.EmailOptInField = value;
                    this.RaisePropertyChanged("EmailOptIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailInfo", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
    [System.SerializableAttribute()]
    public partial class EmailInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfo", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
    [System.SerializableAttribute()]
    public partial class PhoneInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PhoneNumberField;
        
        private int PhoneNumberTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PhoneNumberTypeId {
            get {
                return this.PhoneNumberTypeIdField;
            }
            set {
                if ((this.PhoneNumberTypeIdField.Equals(value) != true)) {
                    this.PhoneNumberTypeIdField = value;
                    this.RaisePropertyChanged("PhoneNumberTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardInfo", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
    [System.SerializableAttribute()]
    public partial class CreditCardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CardNumberField;
        
        private string CardTypeField;
        
        private byte ExpMonthField;
        
        private ushort ExpYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte ExpMonth {
            get {
                return this.ExpMonthField;
            }
            set {
                if ((this.ExpMonthField.Equals(value) != true)) {
                    this.ExpMonthField = value;
                    this.RaisePropertyChanged("ExpMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ushort ExpYear {
            get {
                return this.ExpYearField;
            }
            set {
                if ((this.ExpYearField.Equals(value) != true)) {
                    this.ExpYearField = value;
                    this.RaisePropertyChanged("ExpYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardNumberInUseFault", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
    [System.SerializableAttribute()]
    public partial class CreditCardNumberInUseFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerManagementServiceReference.ICustomerManagementService")]
    public interface ICustomerManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateCustomerResponse")]
        int CreateCustomer(AdventureWorksSalesClient.CustomerManagementServiceReference.CustomerInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<int> CreateCustomerAsync(AdventureWorksSalesClient.CustomerManagementServiceReference.CustomerInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveCustomerResponse")]
        void RemoveCustomer(int businessEntityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveCustomerResponse")]
        System.Threading.Tasks.Task RemoveCustomerAsync(int businessEntityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateEmailAndAssociateWithCustomer" +
            "", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateEmailAndAssociateWithCustomer" +
            "Response")]
        int CreateEmailAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.EmailInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateEmailAndAssociateWithCustomer" +
            "", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateEmailAndAssociateWithCustomer" +
            "Response")]
        System.Threading.Tasks.Task<int> CreateEmailAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.EmailInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveEmail", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveEmailResponse")]
        void RemoveEmail(int emailAddressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveEmail", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveEmailResponse")]
        System.Threading.Tasks.Task RemoveEmailAsync(int emailAddressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreatePhoneAndAssociateWithCustomer" +
            "", ReplyAction="http://tempuri.org/ICustomerManagementService/CreatePhoneAndAssociateWithCustomer" +
            "Response")]
        void CreatePhoneAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreatePhoneAndAssociateWithCustomer" +
            "", ReplyAction="http://tempuri.org/ICustomerManagementService/CreatePhoneAndAssociateWithCustomer" +
            "Response")]
        System.Threading.Tasks.Task CreatePhoneAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/ReplacePhone", ReplyAction="http://tempuri.org/ICustomerManagementService/ReplacePhoneResponse")]
        void ReplacePhone(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo oldPhone, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo newPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/ReplacePhone", ReplyAction="http://tempuri.org/ICustomerManagementService/ReplacePhoneResponse")]
        System.Threading.Tasks.Task ReplacePhoneAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo oldPhone, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo newPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemovePhone", ReplyAction="http://tempuri.org/ICustomerManagementService/RemovePhoneResponse")]
        void RemovePhone(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemovePhone", ReplyAction="http://tempuri.org/ICustomerManagementService/RemovePhoneResponse")]
        System.Threading.Tasks.Task RemovePhoneAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateCreditCardAndAssociateWithCus" +
            "tomer", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateCreditCardAndAssociateWithCus" +
            "tomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AdventureWorksSalesClient.CustomerManagementServiceReference.CreditCardNumberInUseFault), Action="http://tempuri.org/ICustomerManagementService/CreateCreditCardAndAssociateWithCus" +
            "tomerCreditCardNumberInUseFaultFault", Name="CreditCardNumberInUseFault", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksSalesService")]
        int CreateCreditCardAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.CreditCardInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/CreateCreditCardAndAssociateWithCus" +
            "tomer", ReplyAction="http://tempuri.org/ICustomerManagementService/CreateCreditCardAndAssociateWithCus" +
            "tomerResponse")]
        System.Threading.Tasks.Task<int> CreateCreditCardAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.CreditCardInfo toCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/AssociateCreditCardWithCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/AssociateCreditCardWithCustomerResp" +
            "onse")]
        void AssociateCreditCardWithCustomer(int businessEntityId, int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/AssociateCreditCardWithCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/AssociateCreditCardWithCustomerResp" +
            "onse")]
        System.Threading.Tasks.Task AssociateCreditCardWithCustomerAsync(int businessEntityId, int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/DisassociateCreditCardFromCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/DisassociateCreditCardFromCustomerR" +
            "esponse")]
        void DisassociateCreditCardFromCustomer(int businessEntityId, int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/DisassociateCreditCardFromCustomer", ReplyAction="http://tempuri.org/ICustomerManagementService/DisassociateCreditCardFromCustomerR" +
            "esponse")]
        System.Threading.Tasks.Task DisassociateCreditCardFromCustomerAsync(int businessEntityId, int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveCreditCard", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveCreditCardResponse")]
        void RemoveCreditCard(int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagementService/RemoveCreditCard", ReplyAction="http://tempuri.org/ICustomerManagementService/RemoveCreditCardResponse")]
        System.Threading.Tasks.Task RemoveCreditCardAsync(int creditCardId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerManagementServiceChannel : AdventureWorksSalesClient.CustomerManagementServiceReference.ICustomerManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerManagementServiceClient : System.ServiceModel.ClientBase<AdventureWorksSalesClient.CustomerManagementServiceReference.ICustomerManagementService>, AdventureWorksSalesClient.CustomerManagementServiceReference.ICustomerManagementService {
        
        public CustomerManagementServiceClient() {
        }
        
        public CustomerManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateCustomer(AdventureWorksSalesClient.CustomerManagementServiceReference.CustomerInfo toCreate) {
            return base.Channel.CreateCustomer(toCreate);
        }
        
        public System.Threading.Tasks.Task<int> CreateCustomerAsync(AdventureWorksSalesClient.CustomerManagementServiceReference.CustomerInfo toCreate) {
            return base.Channel.CreateCustomerAsync(toCreate);
        }
        
        public void RemoveCustomer(int businessEntityId) {
            base.Channel.RemoveCustomer(businessEntityId);
        }
        
        public System.Threading.Tasks.Task RemoveCustomerAsync(int businessEntityId) {
            return base.Channel.RemoveCustomerAsync(businessEntityId);
        }
        
        public int CreateEmailAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.EmailInfo toCreate) {
            return base.Channel.CreateEmailAndAssociateWithCustomer(businessEntityId, toCreate);
        }
        
        public System.Threading.Tasks.Task<int> CreateEmailAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.EmailInfo toCreate) {
            return base.Channel.CreateEmailAndAssociateWithCustomerAsync(businessEntityId, toCreate);
        }
        
        public void RemoveEmail(int emailAddressId) {
            base.Channel.RemoveEmail(emailAddressId);
        }
        
        public System.Threading.Tasks.Task RemoveEmailAsync(int emailAddressId) {
            return base.Channel.RemoveEmailAsync(emailAddressId);
        }
        
        public void CreatePhoneAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toCreate) {
            base.Channel.CreatePhoneAndAssociateWithCustomer(businessEntityId, toCreate);
        }
        
        public System.Threading.Tasks.Task CreatePhoneAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toCreate) {
            return base.Channel.CreatePhoneAndAssociateWithCustomerAsync(businessEntityId, toCreate);
        }
        
        public void ReplacePhone(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo oldPhone, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo newPhone) {
            base.Channel.ReplacePhone(businessEntityId, oldPhone, newPhone);
        }
        
        public System.Threading.Tasks.Task ReplacePhoneAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo oldPhone, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo newPhone) {
            return base.Channel.ReplacePhoneAsync(businessEntityId, oldPhone, newPhone);
        }
        
        public void RemovePhone(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toDelete) {
            base.Channel.RemovePhone(businessEntityId, toDelete);
        }
        
        public System.Threading.Tasks.Task RemovePhoneAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.PhoneInfo toDelete) {
            return base.Channel.RemovePhoneAsync(businessEntityId, toDelete);
        }
        
        public int CreateCreditCardAndAssociateWithCustomer(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.CreditCardInfo toCreate) {
            return base.Channel.CreateCreditCardAndAssociateWithCustomer(businessEntityId, toCreate);
        }
        
        public System.Threading.Tasks.Task<int> CreateCreditCardAndAssociateWithCustomerAsync(int businessEntityId, AdventureWorksSalesClient.CustomerManagementServiceReference.CreditCardInfo toCreate) {
            return base.Channel.CreateCreditCardAndAssociateWithCustomerAsync(businessEntityId, toCreate);
        }
        
        public void AssociateCreditCardWithCustomer(int businessEntityId, int creditCardId) {
            base.Channel.AssociateCreditCardWithCustomer(businessEntityId, creditCardId);
        }
        
        public System.Threading.Tasks.Task AssociateCreditCardWithCustomerAsync(int businessEntityId, int creditCardId) {
            return base.Channel.AssociateCreditCardWithCustomerAsync(businessEntityId, creditCardId);
        }
        
        public void DisassociateCreditCardFromCustomer(int businessEntityId, int creditCardId) {
            base.Channel.DisassociateCreditCardFromCustomer(businessEntityId, creditCardId);
        }
        
        public System.Threading.Tasks.Task DisassociateCreditCardFromCustomerAsync(int businessEntityId, int creditCardId) {
            return base.Channel.DisassociateCreditCardFromCustomerAsync(businessEntityId, creditCardId);
        }
        
        public void RemoveCreditCard(int creditCardId) {
            base.Channel.RemoveCreditCard(creditCardId);
        }
        
        public System.Threading.Tasks.Task RemoveCreditCardAsync(int creditCardId) {
            return base.Channel.RemoveCreditCardAsync(creditCardId);
        }
    }
}
